# Generated by Django 4.1.3 on 2022-11-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Gender", models.CharField(default="XXX", max_length=100)),
                ("Slug", models.SlugField(blank=True, max_length=100, null=True)),
                ("Category", models.CharField(max_length=100)),
                ("About", models.TextField()),
                ("FamilyIncome", models.IntegerField(default=0, null=True)),
                ("Location", models.CharField(max_length=50)),
                ("City", models.CharField(default="XXX", max_length=50)),
                ("Stream", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254)),
                ("PhoneNumber", models.IntegerField()),
                ("Address", models.TextField()),
                ("Password", models.CharField(max_length=50)),
                ("CurrentClass", models.CharField(max_length=50)),
                ("Marks10th", models.IntegerField()),
                ("Marks12th", models.IntegerField()),
                ("MarksGPA", models.IntegerField()),
                (
                    "Resume",
                    models.FileField(
                        default=None, max_length=500, null=True, upload_to="Resume/"
                    ),
                ),
                (
                    "SupportingPDF",
                    models.FileField(
                        default=None, max_length=500, null=True, upload_to="Degree/"
                    ),
                ),
                (
                    "Picture",
                    models.FileField(
                        default=None, max_length=500, null=True, upload_to="Picture/"
                    ),
                ),
                ("ApplicationProgress", models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
