# Generated by Django 4.1.3 on 2022-11-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CompanyApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="companydetails", name="Interest",),
        migrations.RemoveField(model_name="companydetails", name="Max_Loan",),
    ]
